let allData = [
  {
    id: "1",
    jobTitle: "Mobile First Corp",
    jobRole: "React Native Developer",
    jobType: "Remote • Full-time • $130,000 - $175,000",
    jobDescription: `Build cross-platform mobile applications using React Native. Work on products used by millions of users worldwide.`,
    status: "Not Applied",
  },
  {
    id: "2",
    jobTitle: "WebFlow Agency",
    jobRole: "Web Designer & Developer",
    jobType: " Los Angeles, CA • Part-time • $80,000 - $120,000 ",
    jobDescription: `Create stunning web experiences for high-profile clients. Must have portfolio and experience with modern web design trends.`,
    status: "Not Applied",
  },
  {
    id: "3",
    jobTitle: "DataViz Solutions",
    jobRole: "Data Visualization Specialist",
    jobType: "Boston, MA • Full-time • $125,000 - $165,000",
    jobDescription: `Transform complex data into compelling visualizations. Required skills: D3.js, React, and strong analytical thinking.`,
    status: "Not Applied",
  },
  {
    id: "4",
    jobTitle: "CloudFirst Inc",
    jobRole: "Backend Developer",
    jobType: "Seattle, WA • Full-time • $140,000 - $190,000",
    jobDescription: `Design and maintain scalable backend systems using Python and AWS. Work with modern DevOps practices and cloud infrastructure.`,
    status: "Not Applied",
  },
  {
    id: "5",
    jobTitle: "Innovation Labs",
    jobRole: "UI/UX Engineer",
    jobType: "Austin, TX • Full-time • $110,000 - $150,000",
    jobDescription: `Create beautiful and functional user interfaces for our suite of products. Strong design skills and frontend development expertise required.`,
    status: "Not Applied",
  },
  {
    id: "6",
    jobTitle: "MegaCorp Solutions",
    jobRole: "JavaScript Developer",
    jobType: "New York, NY • Full-time • $130,000 - $170,00",
    jobDescription: `Build enterprise applications with JavaScript and modern frameworks. We offer competitive compensation, health insurance, and professional development opportunities.`,
    status: "Not Applied",
  },
  {
    id: "7",
    jobTitle: "StartupXYZ",
    jobRole: "Full Stack Engineer",
    jobType: "Remote • Full-time • $120,000 - $160,000",
    jobDescription: `Join our fast-growing startup and work on our core platform. Experience with Node.js and React required. Great benefits and equity package included.`,
    status: "Not Applied",
  },
  {
    id: "8",
    jobTitle: "TechCorp Industries",
    jobRole: "Senior Frontend Developer",
    jobType: "San Francisco, CA • Full-time • $130,000 - $175,000",
    jobDescription: `We are looking for an experienced Frontend Developer to build scalable web applications using React and TypeScript. You will work with a talented team on cutting-edge projects.`,
    status: "Not Applied",
  },
  
];

